-- cf_customer
-- A stored procedure dbo.insertCustomer has been created for inserting the data. 

exec dbo.insertCustomer 'james@domian.com', '1qaz***', 'james', 'smith', '95711287', 'mobile', '10.123.34.46'
exec dbo.insertCustomer 'kim@domian.com', '2qaz**!', 'Kim', 'Fernandez', '95444287', 'website', '10.112.34.46'
exec dbo.insertCustomer 'george@domian.com', '1wsx***', 'George', 'William', '98787287', 'mobile', '10.123.45.46'
exec dbo.insertCustomer 'ben@domian.com', '1edc***', 'Ben', 'Stokes', '87651287', 'mobile', '112.321.34.76'
exec dbo.insertCustomer 'william_mary@domian.com', '1okm***', 'William', 'Mary', '76661287', 'mobile', '110.123.112.76'
exec dbo.insertCustomer 'elizabeth@domian.com', '1edc***', 'Elizabeth', 'Paul', '92178287', 'website', '110.123.121.76'
exec dbo.insertCustomer 'david@domian.com', '1edc***', 'David', 'Smith', '90651564', 'website', '110.123.34.121'
exec dbo.insertCustomer 'james@domain.com', '1ewsde***', 'James', 'Paul', '60951564', 'mobile', '113.100.35.111'
exec dbo.insertCustomer 'mathew@domain.com', '2wedrf***', 'Mathew', 'Hayden', '60545164', 'mobile', '67.132.35.12'
exec dbo.insertCustomer 'jones@domain.com', '2wedrf***', 'Indiana', 'Jones', '97653423', 'website', '132.12.122.45'

update cf_customer set approved_date = getDate()-12 where cust_id = 1
update cf_customer set approved_date = getDate()-2 where cust_id = 2
update cf_customer set approved_date = getDate()-23 where cust_id = 3
update cf_customer set approved_date = getDate()-8 where cust_id = 4
update cf_customer set approved_date = getDate()-5 where cust_id = 6
update cf_customer set approved_date = getDate()-16 where cust_id = 7
update cf_customer set approved_date = getDate()-18 where cust_id = 8
update cf_customer set status= 'Rejected', remarks = 'Invalid device type', review_sys_userid=1 where cust_id = 9
update cf_customer set status= 'Rejected', remarks = 'Invalid email', review_sys_userid=1 where cust_id = 10
update cf_customer set status = 'Approved' where cust_id in (1,4,7)
update cf_customer set approved_date=null where status = 'Pending Approval'

-- cf_product
INSERT INTO dbo.cf_product (name, price, qty, sale_start_date, sale_end_date, status, last_updated, create_date)
  VALUES ('Apples', 1.55, 1, '2023-01-12', '2023-12-31', 1, GETDATE(), GETDATE())

INSERT INTO dbo.cf_product (name, price, qty, sale_start_date, sale_end_date, status, last_updated, create_date)
  VALUES ('Oranges', 3.55, 100, '2023-02-12', '2024-12-31', 'L', GETDATE(), GETDATE())

INSERT INTO dbo.cf_product (name, price, qty, sale_start_date, sale_end_date, status, last_updated, create_date)
  VALUES ('Kiwi', 3.50, 200, '2023-01-01', '2024-12-31', 'L', GETDATE(), GETDATE())

INSERT INTO dbo.cf_product (name, price, qty, sale_start_date, sale_end_date, status, last_updated, create_date)
  VALUES ('Mangoes', 10.00, 150, '2023-01-01', '2024-12-31', 'L', GETDATE(), GETDATE())

INSERT INTO dbo.cf_product (name, price, qty, sale_start_date, sale_end_date, status, last_updated, create_date)
  VALUES ('Mangoes', 10.00, 150, '2023-01-01', '2024-12-31', 'L', GETDATE(), GETDATE())

INSERT INTO dbo.cf_product (name, price, qty, sale_start_date, sale_end_date, status, last_updated, create_date)
  VALUES ('Cake', 5.00, 50, '2023-09-01', '2023-10-30', 'L', GETDATE(), GETDATE())

INSERT INTO dbo.cf_product (name, price, qty, sale_start_date, sale_end_date, status, last_updated, create_date)
  VALUES ('Biscuits', 2.00, 150, '2023-09-01', '2023-10-30', 'L', GETDATE(), GETDATE())

INSERT INTO dbo.cf_product (name, price, qty, sale_start_date, sale_end_date, status, last_updated, create_date)
  VALUES ('Cookies', 2.00, 150, '2023-09-01', '2023-10-30', 'L', GETDATE(), GETDATE())

INSERT INTO dbo.cf_product (name, price, qty, sale_start_date, sale_end_date, status, last_updated, create_date)
  VALUES ('Mint', 1.50, 150, '2023-01-01', '2024-12-31', 'L', GETDATE(), GETDATE())
  

-- cf_login_history
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 120)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'iPad', '127.0.0.5', 'Y', GETDATE() - 115)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'Windows11', '13.85.23.254', 'Y', GETDATE() - 100)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'iPhone', '12.10.20.5', 'F', GETDATE() - 105)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'WindowsXp', '115.134.84.3', 'Y', GETDATE() - 100)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'Android', '30.25.1.1', 'Y', GETDATE() - 100)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (7, 'Note', '45.10.10.154', 'F', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (8, 'iPad Mini', '132.85.12.1', 'Y', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Tablet', '113.84.2.1', 'Y', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'iPad', '15.0.0.1', 'F', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'Windows11', '12.10.10.10', 'Y', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'iPhone', '127.0.0.5', 'F', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'WindowsXp', '13.85.23.254', 'Y', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'Android', '12.10.20.5', 'F', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (7, 'Note', '115.134.84.3', 'F', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (8, 'iPad Mini', '30.25.1.1', 'Y', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Tablet', '45.10.10.154', 'F', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'Mobile', '113.84.2.1', 'F', GETDATE() - 95)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'iPad', '15.0.0.1', 'Y', GETDATE() - 80)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'Windows11', '12.10.10.10', 'Y', GETDATE() - 80)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (7, 'iPhone', '127.0.0.5', 'F', GETDATE() - 80)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (8, 'WindowsXp', '13.85.23.254', 'Y', GETDATE() - 80)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (7, 'Android', '12.10.20.5', 'F', GETDATE() - 80)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (8, 'Note', '115.134.84.3', 'Y', GETDATE() - 80)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'iPad Mini', '30.25.1.1', 'Y', GETDATE() - 80)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'Tablet', '45.10.10.154', 'F', GETDATE() - 75)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 60)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'iPad', '113.84.2.1', 'Y', GETDATE() - 50)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'Windows11', '15.0.0.1', 'Y', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'iPhone', '12.10.10.10', 'Y', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'WindowsXp', '127.0.0.5', 'F', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Android', '13.85.23.254', 'Y', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'iPad', '12.10.20.5', 'Y', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'Windows11', '115.134.84.3', 'F', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'iPhone', '30.25.1.1', 'F', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (7, 'WindowsXp', '45.10.10.154', 'Y', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (8, 'Android', '132.85.12.1', 'Y', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'Note', '113.84.2.1', 'Y', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'iPad Mini', '15.0.0.1', 'Y', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Tablet', '12.10.10.10', 'Y', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Android', '127.0.0.5', 'Y', GETDATE() - 45)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Note', '13.85.23.254', 'F', GETDATE() - 40)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'iPad Mini', '12.10.20.5', 'Y', GETDATE() - 39)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Tablet', '115.134.84.3', 'F', GETDATE() - 38)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 37)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'iPad', '45.10.10.154', 'Y', GETDATE() - 37)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'Windows11', '132.85.12.1', 'F', GETDATE() - 37)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (7, 'iPhone', '113.84.2.1', 'Y', GETDATE() - 36)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (8, 'WindowsXp', '15.0.0.1', 'Y', GETDATE() - 36)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'Android', '12.10.10.10', 'Y', GETDATE() - 36)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Note', '127.0.0.5', 'Y', GETDATE() - 36)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'iPad Mini', '13.85.23.254', 'F', GETDATE() - 36)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Tablet', '12.10.20.5', 'Y', GETDATE() - 35)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'iPad', '115.134.84.3', 'Y', GETDATE() - 35)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Windows11', '30.25.1.1', 'Y', GETDATE() - 34)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'iPhone', '45.10.10.154', 'Y', GETDATE() - 34)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'WindowsXp', '132.85.12.1', 'F', GETDATE() - 34)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Android', '113.84.2.1', 'Y', GETDATE() - 33)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Note', '15.0.0.1', 'Y', GETDATE() - 32)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'iPad Mini', '12.10.10.10', 'Y', GETDATE() - 32)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Tablet', '127.0.0.5', 'Y', GETDATE() - 31)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Tablet', '12.10.20.5', 'F', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'iPad', '115.134.84.3', 'Y', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Windows11', '30.25.1.1', 'Y', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'iPhone', '45.10.10.154', 'Y', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'WindowsXp', '132.85.12.1', 'Y', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Android', '113.84.2.1', 'F', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Note', '15.0.0.1', 'Y', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'iPad Mini', '12.10.10.10', 'Y', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Tablet', '127.0.0.5', 'Y', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'Mobile', '13.85.23.254', 'F', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (8, 'iPad', '12.10.20.5', 'F', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Windows11', '115.134.84.3', 'F', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'iPhone', '30.25.1.1', 'Y', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'WindowsXp', '45.10.10.154', 'F', GETDATE() - 30)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Android', '132.85.12.1', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'iPad', '113.84.2.1', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (7, 'Windows11', '15.0.0.1', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (8, 'iPhone', '12.10.10.10', 'F', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (7, 'WindowsXp', '127.0.0.5', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (8, 'Android', '13.85.23.254', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Note', '12.10.20.5', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'iPad Mini', '115.134.84.3', 'F', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Tablet', '30.25.1.1', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Android', '45.10.10.154', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'Note', '132.85.12.1', 'F', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'iPad Mini', '113.84.2.1', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Tablet', '15.0.0.1', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (7, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (8, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Mobile', '12.10.10.10', 'F', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (7, 'Mobile', '45.10.10.154', 'F', GETDATE() - 29)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (8, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 28)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 28)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 28)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 28)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (2, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 28)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (3, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 28)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (4, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 27)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (5, 'Mobile', '115.134.84.3', 'F', GETDATE() - 27)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (6, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 27)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 27)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 27)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 26)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 26)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 26)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 26)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 26)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 26)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 26)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 26)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 25)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 25)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 25)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 25)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 25)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 25)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 24)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 24)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 23)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 23)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 23)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 22)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 21)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 21)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 21)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 21)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 21)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 20)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 19)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 19)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 19)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 18)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 18)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 18)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 18)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 18)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 18)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 18)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 18)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 17)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 17)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 17)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 17)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 17)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 17)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 17)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 16)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 16)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 16)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 16)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 16)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 16)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 16)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 16)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 15)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 15)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 15)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 15)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 15)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 15)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 14)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 14)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 14)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 14)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 14)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 13)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 13)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 13)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 13)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 13)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 12)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 12)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 12)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 12)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 12)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 12)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 12)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 12)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 12)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 12)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 12)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 12)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 11)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 10)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 9)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 8)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 7)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 7)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 7)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 7)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 6)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 6)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 6)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 6)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 5)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 5)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 5)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 5)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 4)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 4)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 4)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 4)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 3)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 3)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 3)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.10.10', 'Y', GETDATE() - 3)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '127.0.0.5', 'Y', GETDATE() - 2)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '13.85.23.254', 'Y', GETDATE() - 2)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '12.10.20.5', 'Y', GETDATE() - 2)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '115.134.84.3', 'Y', GETDATE() - 1)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '30.25.1.1', 'Y', GETDATE() - 1)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '45.10.10.154', 'Y', GETDATE() - 1)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '132.85.12.1', 'Y', GETDATE() - 1)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '113.84.2.1', 'Y', GETDATE() - 0)
INSERT INTO dbo.cf_login_history (cust_id, channel, ipaddress, login_status, create_date)
  VALUES (1, 'Mobile', '15.0.0.1', 'Y', GETDATE() - 0)

-- cf_purchase
INSERT dbo.cf_purchase (cust_id, item_count, total_amt, purchase_date, payment_status, trx_id, payment_method, payment_date, status, create_date) VALUES (2, 1, 1, CAST(1.00 AS Decimal(10, 2)), CAST(N'2023-09-20T00:14:42.237' AS DateTime), N'Completed', NULL, N'Cash', CAST(N'2023-09-20T00:14:42.237' AS DateTime), N'Paid', CAST(N'2023-09-20T00:14:42.237' AS DateTime))
INSERT dbo.cf_purchase (cust_id, item_count, total_amt, purchase_date, payment_status, trx_id, payment_method, payment_date, status, create_date) VALUES (2, 10, CAST(50.50 AS Decimal(10, 2)), CAST(N'2023-09-13T00:15:47.500' AS DateTime), N'Completed', NULL, N'Credit Card', CAST(N'2023-09-12T00:15:47.500' AS DateTime), N'Paid', CAST(N'2023-09-13T00:15:47.500' AS DateTime))
INSERT dbo.cf_purchase (cust_id, item_count, total_amt, purchase_date, payment_status, trx_id, payment_method, payment_date, status, create_date) VALUES (2, 6, CAST(67.50 AS Decimal(10, 2)), CAST(N'2023-09-14T00:16:18.850' AS DateTime), N'Completed', NULL, N'Debit Card', CAST(N'2023-09-14T00:16:18.850' AS DateTime), N'Paid', CAST(N'2023-09-14T00:16:18.850' AS DateTime))
INSERT dbo.cf_purchase (cust_id, item_count, total_amt, purchase_date, payment_status, trx_id, payment_method, payment_date, status, create_date) VALUES (3, 9, CAST(109.50 AS Decimal(10, 2)), CAST(N'2023-09-28T00:16:57.327' AS DateTime), N'Completed', NULL, N'PayPal', CAST(N'2023-09-28T00:16:57.327' AS DateTime), N'Paid', CAST(N'2023-09-28T00:16:57.327' AS DateTime))
INSERT dbo.cf_purchase (cust_id, item_count, total_amt, purchase_date, payment_status, trx_id, payment_method, payment_date, status, create_date) VALUES (4, 9, CAST(109.50 AS Decimal(10, 2)), CAST(N'2023-09-10T00:17:56.047' AS DateTime), N'Failed', NULL, N'PayPal', CAST(N'2023-09-08T00:17:56.047' AS DateTime), N'Failed', CAST(N'2023-09-10T00:17:56.047' AS DateTime))
INSERT dbo.cf_purchase (cust_id, item_count, total_amt, purchase_date, payment_status, trx_id, payment_method, payment_date, status, create_date) VALUES (5, 19, CAST(1090.00 AS Decimal(10, 2)), CAST(N'2023-09-12T00:19:06.427' AS DateTime), N'Completed', NULL, N'Credit Card', CAST(N'2023-09-12T00:19:06.427' AS DateTime), N'Failed', CAST(N'2023-09-12T00:19:06.427' AS DateTime))
INSERT dbo.cf_purchase (cust_id, item_count, total_amt, purchase_date, payment_status, trx_id, payment_method, payment_date, status, create_date) VALUES (6, 12, CAST(18.50 AS Decimal(10, 2)), CAST(N'2023-09-25T03:02:24.543' AS DateTime), N'Failed', NULL, N'PayPal', CAST(N'2023-09-25T03:02:24.543' AS DateTime), N'Refund in way', CAST(N'2023-09-25T03:02:24.543' AS DateTime))
INSERT dbo.cf_purchase (cust_id, item_count, total_amt, purchase_date, payment_status, trx_id, payment_method, payment_date, status, create_date) VALUES (7, 4, CAST(20.00 AS Decimal(10, 2)), CAST(N'2023-09-28T03:04:31.187' AS DateTime), N'Failed', NULL, N'PayPal', CAST(N'2023-09-28T03:04:31.187' AS DateTime), N'Failed', CAST(N'2023-09-28T03:04:31.187' AS DateTime))
INSERT dbo.cf_purchase (cust_id, item_count, total_amt, purchase_date, payment_status, trx_id, payment_method, payment_date, status, create_date) VALUES ( 8, 14, CAST(120.50 AS Decimal(10, 2)), CAST(N'2023-09-08T03:05:05.000' AS DateTime), N'Completed', NULL, N'PayPal', CAST(N'2023-09-08T03:05:05.000' AS DateTime), N'Paid', CAST(N'2023-09-08T03:05:05.000' AS DateTime))

-- cf_purchases_line_item
INSERT INTO dbo.cf_purchases_line_item (purchase_id, pid, name, qty, price, subtotal, create_date)
  VALUES (2, 1, 'Apples', 10, 1.55, 0, GETDATE() - 23)

INSERT INTO dbo.cf_purchases_line_item (purchase_id, pid, name, qty, price, subtotal, create_date)
  VALUES (2, 5, 'Banana', 6, 2.00, 0, GETDATE() - 23)

INSERT INTO dbo.cf_purchases_line_item (purchase_id, pid, name, qty, price, subtotal, create_date)
  VALUES (2, 4, 'Mangoes', 6, 10.00, 0, GETDATE() - 23)

INSERT INTO dbo.cf_purchases_line_item (purchase_id, pid, name, qty, price, subtotal, create_date)
  VALUES (3, 2, 'Oranges', 6, 3.55, 0, GETDATE() - 12)

INSERT INTO dbo.cf_purchases_line_item (purchase_id, pid, name, qty, price, subtotal, create_date)
  VALUES (4, 4, 'Mangoes', 3, 10.00, 0, GETDATE() - 8)

INSERT INTO dbo.cf_purchases_line_item (purchase_id, pid, name, qty, price, subtotal, create_date)
  VALUES (4, 3, 'Kiwi', 3, 3.50, 0, GETDATE() - 8)

INSERT INTO dbo.cf_purchases_line_item (purchase_id, pid, name, qty, price, subtotal, create_date)
  VALUES (5, 3, 'Kiwi', 4, 3.50, 0, GETDATE() - 3)

INSERT INTO dbo.cf_purchases_line_item (purchase_id, pid, name, qty, price, subtotal, create_date)
  VALUES (6, 5, 'Banana', 5, 2.00, 0, GETDATE() - 16)

INSERT INTO dbo.cf_purchases_line_item (purchase_id, pid, name, qty, price, subtotal, create_date)
  VALUES (6, 1, 'Apples', 5, 1.55, 0, GETDATE() - 16)

INSERT INTO dbo.cf_purchases_line_item (purchase_id, pid, name, qty, price, subtotal, create_date)
  VALUES (6, 3, 'Oranges', 5, 3.55, 0, GETDATE() - 16)

INSERT INTO dbo.cf_purchases_line_item (purchase_id, pid, name, qty, price, subtotal, create_date)
  VALUES (5, 2, 'Oranges', 14, 3.55, 0, GETDATE() - 3)

update cf_purchases_line_item set subtotal = qty* price
